{% set name = "Flask-Caching" %}
{% set version = "1.4.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e34f24631ba240e09fe6241e1bf652863e0cff06a1a94598e23be526bc2e4985

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv "

requirements:
  host:
    - python
    - pip
  run:
    - python
    - flask
    - werkzeug >=0.12

test:
  imports:
    - flask_caching
    - flask_caching.backends

about:
  home: https://github.com/sh4nks/flask-caching
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Adds caching support to your Flask application
  doc_url: https://pythonhosted.org/Flask-Caching
  dev_url: https://github.com/sh4nks/flask-caching

extra:
  recipe-maintainers:
    - halldc
